name: Publish Snapshot Artifacts
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  snapshot:
    permissions:
      checks: write
      contents: read
      packages: read
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: maven
      - name: Add msbuild to PATH
        if: ${{ runner.os == 'Windows' }}
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
      - name: "NuGet"
        if: runner.os == 'windows'
        env:
          NugetCredentials: "Username=${{ github.actor }};Password=${{ secrets.GITHUB_TOKEN }}"
        run: |
          echo "NuGetPackageSourceCredentials_gh-ikvmnet=${{ env.NugetCredentials }}" >> $env:GITHUB_ENV
          echo "NuGetPackageSourceCredentials_gh-iterate-ch=${{ env.NugetCredentials }}" >> $env:GITHUB_ENV
      - name: Install Bonjour SDK
        if: ${{ runner.os == 'Windows' }}
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install bonjour -y
      - name: Install WiX Toolset
        if: ${{ runner.os == 'Windows' }}
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install wixtoolset -y
      - name: Install OpenSSL
        if: ${{ runner.os == 'Windows' }}
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: install openssl -y
      - name: Build with Maven
        run: mvn --batch-mode deploy -DskipTests -DskipITs -DskipSign -DskipNotarize
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}